### ISSUE TITLE
Incorrect operation name in WildcardOperationName when path value is the same

### ISSUE THREAD

**Issue by song-hao** [opentracing-contrib/java-jaxrs#114]
https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/OperationNameProvider.java#L74
```
@GET
@Path("/test/{id}/{subid}")
```
When the path parameters in the given URI have same value such as: `/test/1/1`, the operation name will be matched as `/test/{subid}/{subid}`

**Comment by pavolloffay** [comment]
thanks for reporting @song-hao, do you have a fix for this?

**Comment by song-hao** [comment]
@pavolloffay Tried, haven't found the proper way to fix this yet.
