### ISSUE TITLE
WildcardOperationName can't get value of @Path when using interface

### ISSUE THREAD

**Issue by song-hao** [opentracing-contrib/java-jaxrs#120]
Currently, WildcardOperationName won't be able to get value of `@Path` annotation if using API interface as follows:
```
// Interface, TestService.java
@Path("/foo")
public interface TestService {
  @GET
  @Path("/bar")
  Response test();
}

// Implementation, TestServiceImpl.java
public class TestServiceImpl implements TestService {
  public Response test() {
    return Response.ok().build();
  }
}
```
Probably can add some logic after [here](https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/OperationNameProvider.java#L83) to get the value from interface class as follows:
```
if (classPath.isEmpth() || methodPath.isEmpty()) {
  for (Class<?> c : clazz.getInterfaces()) {
    // Get @Path value from interface class
  }
}
```

**Comment by objectiser** [comment]
@song-hao Would you be interested in submitting a PR to fix this?

**Comment by song-hao** [comment]
> @song-hao Would you be interested in submitting a PR to fix this?

Sure, will submit one.
