### ISSUE TITLE
Traced annotation

### ISSUE THREAD

**Issue by Anurag870** [opentracing-contrib/java-jaxrs#124]
Add `@Traced` annotation in this repository on the same lines of 

[opentracing-contrib/java-cdi](https://github.com/opentracing-contrib/java-cdi/blob/master/opentracing-cdi/src/main/java/io/opentracing/contrib/cdi/Traced.java)

[eclipse/microprofile-opentracing](https://github.com/eclipse/microprofile-opentracing/blob/master/api/src/main/java/org/eclipse/microprofile/opentracing/Traced.java)

 [opentracing-contrib/java-spring-cloud#98](https://github.com/opentracing-contrib/java-spring-cloud/issues/98)

**Comment by pavolloffay** [comment]
@Anurag870 hi, what are you proposing?

The `@Traced` annotation is defined in https://github.com/eclipse/microprofile-opentracing/blob/master/api/src/main/java/org/eclipse/microprofile/opentracing/Traced.java.

**Comment by Anurag870** [comment]
@pavolloffay  Thanks. Closing the issue.
