### ISSUE TITLE
Decorate SpanBuilders and Spans instead of only Spans

### ISSUE THREAD

**Issue by dspasojevic** [opentracing-contrib/java-jaxrs#14]
Hi,

We have a customer opentracing implementation that emits events when `SpanBuilder.start` is called and when `Span.finish` is called.

For that reason, it would be convenient if the decorators decorated the `SpanBuilder` when handling a request, and the `Span` when handling a response. The request filters would also be changed to decorate the builder before starting the span.

I don't think that this would change the existing behaviour... would a PR that made this switch be acceptable?

Thanks.

**Comment by pavolloffay** [comment]
Hi,

thanks for raising this issue. I have a couple of comments.

It is important to start span as soon as possible in order to get the most precise timing information. I would be worried that people could execute some expensive code in decorator which would cripple timing data, therefore I don't think that passing a `SpanBuilder` is an appropriate solution to this.

**Comment by dspasojevic** [comment]
Hey. If a decorator is expensive, won't that cost be reflected somewhere in the trace? If the decorator is run after the span is started then it will skew the cost of the newly started span. If it is run before the span is started it will skew the cost of the parent span.

I think you are saying that the latter scenario is naturally worse than the former? I don't understand why that is the case... do you mind clarifying why?

**Comment by pavolloffay** [comment]
If a `SpanBuilder` is passed to decorator span would be started after decoration process:

```
SpanBuilder sb = tracer.buildSpan('foo');
docorator(sb);
Span span = sb.start();
```

so the time spent in decorator is not included in span duration. Note that there is no parent span present so this duration would be lost.

**Comment by dspasojevic** [comment]
If there is no parent span, then, yes, the decorating time will not be accounted for. In a way this seems more "true" as decorating time is not lumped in with time taken to execute measured functionality.

It seems more common that there is almost always a parent span of some sort (local or remote) so this seems like a moot point. That is, client span on the calling end gives total cost to call, including overhead introduced by the container, network, etc.

If you are primarily interested in server spans with no parent then I agree with your point. The choice seems reversed for client spans though?

Thanks for your responses.  Happy to close this out.
