### ISSUE TITLE
log4j2 support

### ISSUE THREAD

**Issue by seho-kim-do-something** [opentracing-contrib/java-jaxrs#140]
Hello,
Is there any plan to support lo4j2? It seems trace with logs not working when I check from UI.
I tried with logback, then I was able to see logs along with my application logs.
Thanks

**Comment by pavolloffay** [comment]
This project purely instruments jax-rs. The integration with the logging framework is out of the scope of this project.

Putting trace context into logs has to be done at tracer initialization time as it requires changing the scope manager implementation https://github.com/quarkusio/quarkus/blob/master/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/MDCScopeManager.java#L11
