### ISSUE TITLE
Cannot get autodiscovery to work in Jersey

### ISSUE THREAD

**Issue by stephen00001** [opentracing-contrib/java-jaxrs#141]
Hi,

I've been trying to get the auto discovery feature to work.
I've followed your [test ](https://github.com/opentracing-contrib/java-jaxrs ) example and am using Jaeger and Jersey 2.31.
However when I call the REST endpoint I only see the child span in Jaeger. If I pass in a parent span from the client I see that logged also as a separate span. I thought the child span would appear as a child of the parent in Jaeger UI.
Should a span not automatically be created for each endpoint and one called "helloRenamed" (@Traced(operationName = "helloRenamed"))? "Tracing can be automatically enabled by adding the following dependency on classpath. This mechanism requires a tracer to be registered in GlobalTracer. This is typically done in ServletContextListener."
Maybe I'm misunderstanding this.

I've created the servlet filter. Not sure if I need to create the dynamic feature, but I've done this as well.
Note: I don't see the output from the DynamicFeature configure method ("TracingInitializer called......") so not sure if this is actually being called.
Main code is below. I'd appreciate some guidance and education on this.

Thanks

```
public class OpenTracingContextInitializer implements javax.servlet.ServletContextListener{
    
    @Override
  public void contextInitialized(ServletContextEvent servletContextEvent) {
    io.opentracing.Tracer tracer = getJaegerTracer();
    boolean registered = GlobalTracer.registerIfAbsent(tracer); // or preferably use CDI

    ServletContext servletContext = servletContextEvent.getServletContext();
    Dynamic filterRegistration = servletContext
        .addFilter("tracingFilter", new SpanFinishingFilter());
    filterRegistration.setAsyncSupported(true);
    filterRegistration.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST, DispatcherType.ASYNC), false, "*");
  
  }
}

@Provider
public class TracingInitializer implements DynamicFeature {

  private final ServerTracingDynamicFeature serverTracingDynamicFeature =
      new ServerTracingDynamicFeature.Builder(GlobalTracer.get())
          .withOperationNameProvider(ClassNameOperationName.newBuilder())
      .build();

  @Override
  public void configure(ResourceInfo resourceInfo, FeatureContext context) {
    System.out.println("TracingInitializer called......");
      serverTracingDynamicFeature.configure(resourceInfo, context);
    
  }
  
  
   @GET
    @Path("/hello")
    @Produces(MediaType.TEXT_PLAIN)
    @Traced(operationName = "helloRenamed")
    public Response hello() {
        
        Span childSpan = GlobalTracer.get().buildSpan("businessOperation")
          .start();

   // business logic
        childSpan.finish();
        return Response.status(Response.Status.OK).entity("hello").build();
    }
``

**Comment by pavolloffay** [comment]
hi @stephen00001 could you please be more specific? What is not working? You don't see any spans for JAX-RS server resources?

**Comment by stephen00001** [comment]
The only traces I'm seeing are the ones I create in the hello method or in client using the following or similar code. ``` Span childSpan = GlobalTracer.get().buildSpan("businessOperation")
          .start(); ```   
I was under the impression that with this plugin it would automatically create a span per endpoint without the need to manually create spans (unless required). Maybe I'm misunderstanding the purpose of the auto discovery. There is nothing created in Jaeger called "helloRenamed" that I have found.
Hope this is a bit clearer.

**Comment by pavolloffay** [comment]
It seems like the tracing isn't configured properly. Try to follow examples in this repository.

Then I would suggest debugging the application and see whether jax-rs filters are being used.

**Comment by stephen00001** [comment]
Given that there is a DiscoverableServerTracingFeature class in the discovery package I'm assuming I do not need to create TracingInitializer. I just need to add the filter to set the Global tracer, and opentracing-jaxrs2-discovery jar in the pom. Is this correct? 
I know the filter is being called and the tracer is set.

Am I also correct in assuming that I don't need the following code in the context listener as it is already in the DiscoverableSpanFinishingFilter  class?

```
ServletContext servletContext = servletContextEvent.getServletContext();
    Dynamic filterRegistration = servletContext
        .addFilter("tracingFilter", new SpanFinishingFilter());
    filterRegistration.setAsyncSupported(true);
    filterRegistration.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST, DispatcherType.ASYNC), false, "*");
```
So in theory, once I add the opentracing-jaxrs2-discovery jar to classpath and add a tracer to the Globaltracer in the context filter the basics should work?
Is the @Traced tag only required to set a name or to mark it not to be automatically traced?

Thanks

**Comment by pavolloffay** [comment]
If the auto-discovery does not work for you, then you might be initializing JAX-RS in a custom way that is not supported by this project. If you could share a full codebase (with no business logic) then I would be able to tell more.

**Comment by stephen00001** [comment]
Ok thanks. I've a sample project that I'll send over shortly. Appreciated

**Comment by stephen00001** [comment]
Hi Pavol,
Sample project attached.

[RESTFulExample.zip](https://github.com/opentracing-contrib/java-jaxrs/files/4766163/RESTFulExample.zip)

Thanks

**Comment by stephen00001** [comment]
Got it working in the end. Needed to register the TracingInitializer class.
```
public class ApplicationConfig extends ResourceConfig {

    public ApplicationConfig() {
        register(com.test.TracingInitializer.class);
    }
}
```
web.xml
```
<init-param>
    <param-name>javax.ws.rs.Application</param-name>
    <param-value>com.test.config.ApplicationConfig</param-value>
</init-param>
```
