### ISSUE TITLE
String comparison using equals

### ISSUE THREAD

**Issue by jasondlee** [opentracing-contrib/java-jaxrs#145]
I could be missing something subtle, but this looks like a bug (String comparison using `==` instead of `.equals()` ).

https://github.com/opentracing-contrib/java-jaxrs/blob/196c72d484691f615bb354ca8e46b9b305726283/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/OperationNameProvider.java#L93

**Comment by rishi-lgtm** [comment]
> I could be missing something subtle, but this looks like a bug (String comparison using `==` instead of `.equals()` ).
> 
> https://github.com/opentracing-contrib/java-jaxrs/blob/196c72d484691f615bb354ca8e46b9b305726283/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/OperationNameProvider.java#L93

what if m.getName is Null. [.equals] will throw a NPE .

**Comment by pavolloffay** [comment]
would you like to submit a fix?

**Comment by rishi-lgtm** [comment]
> would you like to submit a fix?

Can you please assign to me?

**Comment by rishi-lgtm** [comment]
@pavolloffay Can u provide me access.
i am getting below error while pusing.
`remote: Permission to opentracing-contrib/java-jaxrs.git denied to rishi-lgtm.
fatal: unable to access 'https://github.com/opentracing-contrib/java-jaxrs.git/': The requested URL returned error: 403`

**Comment by pavolloffay** [comment]
The repository is public you should be able to fork it and submit a PR from your fork.

**Comment by rishi-lgtm** [comment]
Have raised a PR
https://github.com/opentracing-contrib/java-jaxrs/pull/146

**Comment by pavolloffay** [comment]
Done in #146
