### ISSUE TITLE
Specify a priority on the filters

### ISSUE THREAD

**Issue by johnament** [opentracing-contrib/java-jaxrs#15]
JAX-RS 2.0 allows filters to specify priority, and priority drives the execution order - http://docs.oracle.com/javaee/7/api/javax/ws/rs/Priorities.html

OpenTracing JAX-RS doesn't leverage this and I believe it should.  I would like to write a filter that uses the value of the tracer that's been loaded.  I can specify mine is in the user area, but I think OpenTracing should be done in the `HEADER_DECORATOR` phase.

**Comment by pavolloffay** [comment]
Hi @johnament thanks for pointing to this issue. I have submitted #20 to fix it. 

There are still some tracing improvement which can be made Currently, it does not trace requests for no URL mapping and probably secured endpoints. I'm wondering how it can be done purely with jax-rs. Can be `ContainerRequestFilter` configured to run before auth filter?

**Comment by johnament** [comment]
Yes, that's actually the point of the priority annotation.  You can control when in the chain it executes.  I'm not sure which auth filter you're referring to though.
