### ISSUE TITLE
Use GlobalTracer as a default configuration

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-jaxrs#21]
`ServerTracingDynamicFeature` is annotated with `@Provider` but there si no suitable constructor [1].

We might provide a default constructor:
```java
ServerTracingDynamicFeature() {
   this(new Builder(GlobalTracer.get()));
}
```

Then the issue might be how to exclude registration if users would like to use custom tracing configuration (e.g. span decorators)

[1]: http://download.oracle.com/otn-pub/jcp/jaxrs-1.0-fr-eval-oth-JSpec/jaxrs-1.0-final-spec.pdf section 4.1.1

cc @jpkrohling @johnament

**Comment by akihikokuroda** [comment]
I can not use this library without fixing missing default constructor.  It causes a NPE in my environment.  I temporary patched like:

```
    private static Builder builder;
    public ServerTracingDynamicFeature(){}
    private ServerTracingDynamicFeature(Builder builder1) {
        builder = builder1;
    }
```
I'm not sure if it's a right fix but it works for me for now.

**Comment by johnament** [comment]
@akihikokuroda i'm curious, what error do you receive?  JAX-RS impls should ignore invalid providers.

**Comment by akihikokuroda** [comment]
It generates some error log entries and the provider is ignored (I assume).  I assumed that the class is not registered because of the error but I'm not sure.  I'll check if it still works even if it generates  error log entries.

**Comment by johnament** [comment]
It should.  The log messages are simply that - your container letting you know something's a bit off.

**Comment by akihikokuroda** [comment]
OK  Thank.  I'll try.

**Comment by akihikokuroda** [comment]
ServerTracingDynamicFeature() must be public

**Comment by pavolloffay** [comment]
@akihikokuroda  should be fixed in https://github.com/opentracing-contrib/java-jaxrs/pull/24. I will trigger a new release.
