### ISSUE TITLE
Multiple ServerTracingDynamicFeature instances

### ISSUE THREAD

**Issue by akihikokuroda** [opentracing-contrib/java-jaxrs#25]
The JAX-RS framework seems instantiating the ServerTracingDynamicFeature instance by the default constructor and uses the instance to call the configure method.  This instance has its own Builder instance instantiated by the "Builder(Tracer tracer)" and it is referenced in the configure method.  

When I call  (following the README)
```
ServerTracingDynamicFeature.Builder
   .traceAll(yourPreferredTracer)
   .withDecorators(Arrays.asList(ServerSpanDecorator.HTTP_WILDCARD_PATH_OPERATION_NAME, 
    ServerSpanDecorator.STANDARD_TAGS))
    .build();

```
, this instantiates another instance of the ServerTracingDynamicFeature and an inner Builder class.  This instance is not used by the framework for the configure call and the "tradeAll"  or "withDecorators" method call don't have effects.

**Comment by pavolloffay** [comment]
I think there are two solutions to this. 

* disable auto discovery 
* remove `@Provider` and maybe introduce new artifact with Feature annotated with `@Provider` for auto configuration.

cc @jpkrohling  @johnament

**Comment by pavolloffay** [comment]
@akihikokuroda could you please share your jax-rs configuration? So there are two `ServerTracingDynamicFeature` registered at runtime, one registered explicitly and second default picked by auto-discovery (because class is annotated with `@Provider`)

**Comment by akihikokuroda** [comment]
@pavolloffay I'm using IBM Liberty and its JAX-RS feature. (https://developer.ibm.com/wasdev/downloads/#asset/features-com.ibm.websphere.appserver.jaxrs-2.0)
