### ISSUE TITLE
In process propagation

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-jaxrs#27]
Instrumentation currently does not use in-process propagation for an active span. 

Some references:
https://github.com/opentracing/opentracing-java/pull/115, https://github.com/opentracing-contrib/java-spanmanager

**Comment by malafeev** [comment]
+1

**Comment by malafeev** [comment]
On client side:
I assume that span should be activated in `ClientRequestFilter`
and deactivated in `ClientResponseFilter`.
But will this two filters always run in the same thread?

**Comment by pavolloffay** [comment]
hm.. I thought this is done. I will look at it today.

**Comment by pavolloffay** [comment]
Fixed in #36
