### ISSUE TITLE
Rename repository should include opentracing

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-jaxrs#3]
As discussed in https://github.com/opentracing-contrib/java-jaxrs/pull/2#issuecomment-267301826 it should be good to include `opentracing` in the repository name for better searchability. 

Proposed repository names:
1. `opentracing-jaxrs`
2. `opentracing-java-jaxrs`

**Comment by pavolloffay** [comment]
@bensigelman what do you think?

**Comment by bensigelman** [comment]
@pavolloffay I was hoping – perhaps naively – that the `opentracing-contrib` org would make that clear enough. E.g., imagine if all of the below have an `opentracing-` prefix as well:

![image](https://cloud.githubusercontent.com/assets/2251553/21363353/09383b06-c6a1-11e6-8bb8-d9a07c334739.png)

Thoughts?

**Comment by pavolloffay** [comment]
> imagine if all of the below have an opentracing- prefix as well:

See https://github.com/opentracing 

When you are already looking at OT contrib org it's fine you probably found repository you needed.

Try to find `opentracing globaltracer` https://github.com/search?utf8=%E2%9C%93&q=opentracing+globaltracer&type=Repositories&ref=advsearch&l=&l= 

..no result.

Why? Github probably does not add org name to its search algorithm.

**Comment by sjoerdtalsma** [comment]
I would love to have the maven artifact names better aligned with the repository name.
It is rather hard to find the github 'home' for artifacts.
Also often people either have to look at pom.xml or look at README on how to include the artifacts, while the naming could be more in line.

**Comment by bensigelman** [comment]
@pavolloffay IMO the github search is just broken. Google does just fine FWIW: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=opentracing+globaltracer+java

@sjoerdtalsma standardization of maven artifact names would be great. I think we just need someone to think about it for a few minutes and propose something rational... it's been ad hoc so far.

**Comment by sjoerdtalsma** [comment]
@bensigelman I think the maven artifact should at least have the opentracing prefix to be clear about the dependency.
Following that, I don't think the suggestion @pavolloffay made is that bad. If it improves github search, that may be an additional benefit.

I _do_ like the current technology distinction though (the `java-` prefix), but that too is unnecessary in the purist argument, as github already marks a repo being a 'java' repo. Again, not saying to remove the `java-` prefix, but I would not mind a `java-opentracing-...` prefix either.

I'm fine with what you decide either way, but maybe there needs to be something explicit added to the `meta` repo regarding this?

**Comment by pavolloffay** [comment]
Closing, not relevant at the moment.
