### ISSUE TITLE
Update OpenTracing API to 0.31.0 

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-jaxrs#61]
The current master depends on MP-OpenTracing which uses OT 0.30.0. MP does not use any OT directly it just exposes tracer bean to the application.

Do we want to bump TO version even though MP will depend on the old version?

**Comment by objectiser** [comment]
Sounds reasonable.

**Comment by pavolloffay** [comment]
Ok, then I will merge `v0.31.0` to master and release under 0.1.0.

If there will be any changes required to make MP impl work in swarm. We can create a branch and release under `0.0.x`.

**Comment by mpetazzoni** [comment]
I think this can be closed, given the release of 0.1.0 yesterday.

**Comment by pavolloffay** [comment]
@mpetazzoni thanks, closing.
