### ISSUE TITLE
Spans created with jaxrs instrumentation don't include component tag

### ISSUE THREAD

**Issue by kevinearls** [opentracing-contrib/java-jaxrs#76]
I have a simple wildfly-swarm application (https://github.com/kevinearls/SimpleSwarmWithTracing) that uses the jaxrs instrumentation.   The spans created by the instrumentation do not include the component tag, and may be missing several other tags.  (I'm not sure exactly which tags are required, but the EJB instrumentation creates several more tags than the jaxrs instrumentation does.)

**Comment by pavolloffay** [comment]
The component tag is not defined in Microprofile, hence is not added here (to pass TCK). 

> and may be missing several other tags. (I'm not sure exactly which tags are required, but the EJB instrumentation creates several more tags than the jaxrs instrumentation does.)

Please be specific what tags are missing regarding the spec?

**Comment by pavolloffay** [comment]
https://github.com/eclipse/microprofile-opentracing/issues/65

**Comment by jpkrohling** [comment]
The CDI, EJB and Servlet libraries include the component tag, like this:

https://github.com/opentracing-contrib/java-web-servlet-filter/blob/master/opentracing-web-servlet-filter/src/main/java/io/opentracing/contrib/web/servlet/filter/ServletFilterSpanDecorator.java#L79

As such, I would expect to see the same for the JAX-RS integration.

**Comment by pavolloffay** [comment]
It will be included in MP-OT 1.1. Will be fixed here in https://github.com/opentracing-contrib/java-jaxrs/pull/85
