### ISSUE TITLE
Exceptional async server spans are not marked with an error tag or HTTP status

### ISSUE THREAD

**Issue by rnorth** [opentracing-contrib/java-jaxrs#91]
Firstly, thanks for this useful library - it's helped us very quickly instrument Dropwizard services for OpenTracing!

We're seeing a bit of an edge case, perhaps. We have the following simple test endpoints:

```
    @GET
    @Path("/runtime")
    public void throwRuntimeException() {
        throw new RuntimeException();
    }

    @GET
    @Path("/runtime/async")
    public void throwRuntimeException(@Suspended AsyncResponse async) {
        new Thread(() -> {
            sleepUninterruptibly(5, SECONDS);
            async.resume(new RuntimeException());
        }).start();
    }
```

(N.B. We have an exception mapper in place - not sure if this is relevant)

What we're seeing is that:

1. the sync endpoint produces a span with the `error` tag set to true, and there is no HTTP status set
1. the async endpoint produces a span without an `error` tag - in fact there's no way to tell that the span was an error without looking at the HTTP response code recorded by a _caller's_ client span.

I'd have expected that at least the `error` tag would be set on the async server span. (It would be nice if the HTTP status code were set too, but this is really a separate question).

It _feels like_ `SpanFinishingFilter.SpanFinisher` is the right place to set the error tag. At present, it just finishes the span without modifying it, regardless of the response:
```
    @Override
    public void onComplete(AsyncEvent event) throws IOException {
        spanWrapper.finish();
    }
```

I'm considering raising a PR to amend to:
```
    @Override
    public void onComplete(AsyncEvent event) throws IOException {
        if (event.getSuppliedResponse() instanceof Response) {
            final int status = ((Response) event.getSuppliedResponse()).getStatus();
            if (status >= 500) {
              Tags.ERROR.set(spanWrapper.get(), true);
            }
        }

        spanWrapper.finish();
    }
```
I don't really like having to use the status code, so I wondered if you have any different suggestions!

**Comment by pavolloffay** [comment]
> the sync endpoint produces a span with the error tag set to true, and there is no HTTP status set

Http code should be always set  https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/SpanFinishingFilter.java#L58. Would you like to provide a reproducer for it? 

> I don't really like having to use the status code, so I wondered if you have any different suggestions! 

Maybe use `onError` handler?
https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/SpanFinishingFilter.java#L98

**Comment by rnorth** [comment]
Aha, I was attempting to create a repro for this issue and finding that it was unexpectedly working - it seems that #98 addresses the core problem in this issue.

Will close.
