### ISSUE TITLE
Is there any reason to depend on org.eclipse.microprofile.opentracing.Traced?

### ISSUE THREAD

**Issue by philipzhaoTS** [opentracing-contrib/java-jaxrs#93]
What is the motivation that it need to depend this interface? Otherwise, I did not see why such interface was useful.

**Comment by pavolloffay** [comment]
> did not see why such interface was useful.

Can you please explain why?

It's useful to override operation name and disable tracing per endpoint.

**Comment by jpkrohling** [comment]
Note that it's not an interface, but an annotation.

**Comment by pavolloffay** [comment]
I am closing this as it seems not relevant.
