### ISSUE TITLE
No Trace when @Path concatenation between class and methods in a particular case

### ISSUE THREAD

**Issue by BenjaminRevertegat** [opentracing-contrib/java-jaxrs#95]
Hi,

A project that I instrument has @Path annotation on a class and its methods, but one of this methods have an empty path. like this:
```java
@Path(value = "foo/bar")
public class myClass {

    @Path(value = "")
    public void myMethod()
```
Which gives me as a result no span creation

but with something like this:
```java
@Path(value = "foo")
public class myClass {

    @Path(value = "bar")
    public void myMethod()
```
All is working well !

Any idea to fix that ?

**Comment by pavolloffay** [comment]
I have tried this on the example we have in this repository: https://github.com/opentracing-contrib/java-jaxrs/compare/master...pavolloffay:issue-95?expand=1 

It produces span with an operation name `/foo/bar`
```
{
  "context" : {
    "traceId" : 1,
    "spanId" : 2
  },
  "parentId" : 0,
  "startMicros" : 1535640702736000,
  "finishMicros" : 1535640706381000,
  "tags" : {
    "http.url" : "http://localhost:3000/foo/bar",
    "http.status_code" : 200,
    "component" : "jaxrs",
    "span.kind" : "server",
    "http.method" : "GET"
  },
  "logs" : [ ],
  "operationName" : "/foo/bar"
}
```

**Comment by pavolloffay** [comment]
However I had to annotate the method with `@GET`

**Comment by BenjaminRevertegat** [comment]
Your operationName should be ExampleHandler/myMethod ?

In my case, I have an ```@POST```. I don't understand because change the ```@Path(value)``` is the only thing I modify...

**Comment by pavolloffay** [comment]
If you provide a reproducer I could have a look.

**Comment by BenjaminRevertegat** [comment]
Thank you for that, but I'm an intern and I finish at the end of the month and unfortunately I won't have time to provide a reproducer :/ , sorry.

**Comment by pavolloffay** [comment]
@BenjaminRevertegat I will close it as I failed to reproduce. Even the provided example is wrong as it should have @GET or other verb annotation.
